# Generated by Django 2.1.15 on 2020-08-21 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itassetnewapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extededuser',
            new_name='extedenduser',
        ),
    ]
