# Generated by Django 2.1.15 on 2020-08-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itassetnewapp', '0002_auto_20200821_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extedenduser',
            old_name='email_id',
            new_name='email',
        ),
    ]
