# Generated by Django 2.1.15 on 2020-08-22 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('itassetnewapp', '0005_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 22, 11, 18, 43, 453974, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
