# Generated by Django 2.1.15 on 2020-08-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassetnewapp', '0008_auto_20200822_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='webserver',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
