# Generated by Django 2.1.15 on 2020-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itassetnewapp', '0009_asset_webserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='webserver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
